<robot name="acker" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="width" value="0.161" />
    <xacro:property name="length" value="0.347" />
    <xacro:property name="height" value="0.0855" />
    <xacro:property name="wheel_diameter" value="0.073" />
    <xacro:property name="wheel_thickness" value="0.03" />
    <xacro:property name="pi" value="3.141592" />

   <material name="white">
        <color rgba= "1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba= "1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba= "0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba= "0 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0"/>    
    </joint>

    <!-- Example link -->
    <link name="base_footprint">
    </link>

    <link name="chassis">
        <visual>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${length} ${width} ${height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="600"/>
            <inertia ixx="84.22" ixy="0.576" ixz="5.383" iyy="102.589" iyz="2.736" izz="43.303"/>
        </inertial>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="base_link_to_chasis" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin rpy="0 0 0" xyz="0 0 ${(height/2)+(wheel_diameter/2)}"/>
    </joint>

    <!-- laser_frame -->
    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${(height/2)}" rpy="0 0 0"/>  
    </joint>

    <!--Mounts-->
    <xacro:macro name="wheel" params="prefix suffix x y mode">

        <link name="${prefix}_${suffix}_mount">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.01"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.01"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>
        <joint name="${prefix}_${suffix}_mount_joint" type="${mode}">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="chassis"/>
            <child link="${prefix}_${suffix}_mount"/>
            <origin xyz="${x} ${y} -${height/2}" rpy="0 0 0"/>
        </joint>

        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>
        <gazebo reference="${prefix}_${suffix}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="${prefix}_${suffix}_mount"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

    </xacro:macro>
    <xacro:wheel prefix="front" suffix="left" x="0.1388" y="0.0805" mode="continuous"/>
    <xacro:wheel prefix="front" suffix="right" x="0.1388" y="-0.0805" mode="continuous"/>
    <xacro:wheel prefix="back" suffix="left" x="-0.1388" y="0.0805" mode="fixed"/>
    <xacro:wheel prefix="back" suffix="right" x="-0.1388" y="-0.0805" mode="fixed"/>

    <gazebo>
        <plugin name="gertrud_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
            </ros>
            <update_rate>30</update_rate>
            <joint_name>front_left_wheel_joint</joint_name>
            <joint_name>front_right_wheel_joint</joint_name>
            <joint_name>back_left_wheel_joint</joint_name>
            <joint_name>back_right_wheel_joint</joint_name>
            <joint_name>front_left_mount_joint</joint_name>
            <joint_name>front_right_mount_joint</joint_name>
            <joint_name>back_left_mount_joint</joint_name>
            <joint_name>back_right_mount_joint</joint_name>
        </plugin>
        <plugin name="gazebo_ros_joint_pose_trajectory"
                filename="libgazebo_ros_joint_pose_trajectory.so">
            <ros>
            </ros>
            <update_rate>2</update_rate>
        </plugin>
    </gazebo>

    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
        <sensor name="laser" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
						<!--samples> is the number of simulated lidar rays to generate per complete laser sweep cycle.-->
                        <samples>360</samples>
						<!--resolution>: this number is multiplied by samples to determine the number range data points.-->
                        <resolution>1</resolution>
						<min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo>

        <plugin name='ackermann_drive' filename='libgazebo_ros_ackermann_drive.so'>


            <update_rate>100.0</update_rate>

            <!-- wheels -->
            <front_left_joint>front_left_wheel_joint</front_left_joint>
            <front_right_joint>front_right_wheel_joint</front_right_joint>
            <rear_left_joint>back_left_wheel_joint</rear_left_joint>
            <rear_right_joint>back_right_wheel_joint</rear_right_joint>
            <left_steering_joint>front_left_mount_joint</left_steering_joint>
            <right_steering_joint>front_right_mount_joint</right_steering_joint>

            <!-- Max absolute steer angle for tyre in radians-->
            <!-- Any cmd_vel angular z greater than this would be capped -->
            <max_steer>0.6458</max_steer>

            <!-- Max absolute steering angle of steering wheel -->
            <max_steering_angle>7.85</max_steering_angle>

            <!-- Max absolute linear speed in m/s -->
            <max_speed>20</max_speed>

            <!-- PID tuning -->
            <left_steering_pid_gain>5000 1000 500</left_steering_pid_gain>
            <left_steering_i_range>0 0</left_steering_i_range>
            <right_steering_pid_gain>5000 1000 500</right_steering_pid_gain>
            <right_steering_i_range>0 0</right_steering_i_range>
            <linear_velocity_pid_gain>10 5 5</linear_velocity_pid_gain>
            <linear_velocity_i_range>0 0</linear_velocity_i_range>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <publish_distance>true</publish_distance>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

        </plugin>
    </gazebo>


</robot>
